/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

/**
 *
 * @author Alan Basilio
 */
public class busqueda extends javax.swing.JPanel
{

    /**
     * Creates new form NewJPanel
     */
    public busqueda()
    {
        initComponents();
    }
    
    private String usuario;
    private String categoria;

    public void setUsuario(String usuario)
    {
        this.usuario = usuario;
    }

    public void setCategoria(String categoria)
    {
        this.categoria = categoria;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labelAuto1 = new javax.swing.JLabel();
        labelModelo4 = new javax.swing.JLabel();
        labelAuto4 = new javax.swing.JLabel();
        labelAuto3 = new javax.swing.JLabel();
        labelModelo3 = new javax.swing.JLabel();
        labelModelo2 = new javax.swing.JLabel();
        labelAuto2 = new javax.swing.JLabel();
        labelModelo1 = new javax.swing.JLabel();
        labelAuto5 = new javax.swing.JLabel();
        labelModelo5 = new javax.swing.JLabel();
        labelAuto6 = new javax.swing.JLabel();
        labelModelo6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        labelAuto1.setBackground(new java.awt.Color(255, 255, 255));
        labelAuto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto1MouseClicked(evt);
            }
        });

        labelModelo4.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo4.setText("Auto 4");
        labelModelo4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo4MouseClicked(evt);
            }
        });

        labelAuto4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto4MouseClicked(evt);
            }
        });

        labelAuto3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto3MouseClicked(evt);
            }
        });

        labelModelo3.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo3.setText("Auto 3");
        labelModelo3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo3MouseClicked(evt);
            }
        });

        labelModelo2.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo2.setText("Auto 2");
        labelModelo2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo2MouseClicked(evt);
            }
        });

        labelAuto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto2MouseClicked(evt);
            }
        });

        labelModelo1.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo1.setText("Auto 1");
        labelModelo1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo1MouseClicked(evt);
            }
        });

        labelAuto5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto5MouseClicked(evt);
            }
        });

        labelModelo5.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo5.setText("Auto 5");
        labelModelo5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo5MouseClicked(evt);
            }
        });

        labelAuto6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto6.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto6MouseClicked(evt);
            }
        });

        labelModelo6.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo6.setText("Auto 6");
        labelModelo6.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAuto1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(labelAuto2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(labelAuto3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(labelModelo2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(labelModelo3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAuto4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(labelAuto5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(labelAuto6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelModelo4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(labelModelo5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(labelModelo6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAuto1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAuto2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAuto3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelModelo1)
                    .addComponent(labelModelo2)
                    .addComponent(labelModelo3))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAuto4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAuto5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAuto6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelModelo4)
                    .addComponent(labelModelo5)
                    .addComponent(labelModelo6))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelAuto1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto1MouseClicked
    {//GEN-HEADEREND:event_labelAuto1MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
    }//GEN-LAST:event_labelAuto1MouseClicked

    private void labelModelo4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo4MouseClicked
    {//GEN-HEADEREND:event_labelModelo4MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
    }//GEN-LAST:event_labelModelo4MouseClicked

    private void labelAuto4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto4MouseClicked
    {//GEN-HEADEREND:event_labelAuto4MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
    }//GEN-LAST:event_labelAuto4MouseClicked

    private void labelAuto3MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto3MouseClicked
    {//GEN-HEADEREND:event_labelAuto3MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
    }//GEN-LAST:event_labelAuto3MouseClicked

    private void labelModelo3MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo3MouseClicked
    {//GEN-HEADEREND:event_labelModelo3MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
    }//GEN-LAST:event_labelModelo3MouseClicked

    private void labelModelo2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo2MouseClicked
    {//GEN-HEADEREND:event_labelModelo2MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
    }//GEN-LAST:event_labelModelo2MouseClicked

    private void labelAuto2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto2MouseClicked
    {//GEN-HEADEREND:event_labelAuto2MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
    }//GEN-LAST:event_labelAuto2MouseClicked

    private void labelModelo1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo1MouseClicked
    {//GEN-HEADEREND:event_labelModelo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelModelo1MouseClicked

    private void labelAuto5MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto5MouseClicked
    {//GEN-HEADEREND:event_labelAuto5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelAuto5MouseClicked

    private void labelModelo5MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo5MouseClicked
    {//GEN-HEADEREND:event_labelModelo5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelModelo5MouseClicked

    private void labelAuto6MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto6MouseClicked
    {//GEN-HEADEREND:event_labelAuto6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelAuto6MouseClicked

    private void labelModelo6MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo6MouseClicked
    {//GEN-HEADEREND:event_labelModelo6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelModelo6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAuto1;
    private javax.swing.JLabel labelAuto2;
    private javax.swing.JLabel labelAuto3;
    private javax.swing.JLabel labelAuto4;
    private javax.swing.JLabel labelAuto5;
    private javax.swing.JLabel labelAuto6;
    private javax.swing.JLabel labelModelo1;
    private javax.swing.JLabel labelModelo2;
    private javax.swing.JLabel labelModelo3;
    private javax.swing.JLabel labelModelo4;
    private javax.swing.JLabel labelModelo5;
    private javax.swing.JLabel labelModelo6;
    // End of variables declaration//GEN-END:variables
}
