package Interface;

import javax.swing.JOptionPane;

/**
 *
 * @author Alan Basilio
 */
public class Carga extends javax.swing.JFrame
{

    /**
     * Creates new form Carga
     */
    public Carga()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        LoadindLabel = new javax.swing.JLabel();
        Contador = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LoadindLabel.setText("Cargando...");

        Contador.setText("0%");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Materials/Logo Vionet Motors.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LoadindLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Contador)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoadindLabel)
                    .addComponent(Contador))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 400));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Materials/pexels-daniel-andraski-197681005-13275527.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 450, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        Carga carga = new Carga();
        carga.setVisible(true);
        
            try
            {
                for (int i = 0; i < 100; i++)
                {
                    Thread.sleep(70);
                    carga.Contador.setText(i + "%");
                    
                    if (i == 10)
                    {
                        carga.LoadindLabel.setText("Llamando los Módulos...");
                    }
                    if (i == 20)
                    {
                        carga.LoadindLabel.setText("Cargando Módulos...");
                    }
                    if (i == 50)
                    {
                        carga.LoadindLabel.setText("Conectando a la Base de Datos...");
                    }
                    if (i == 70)
                    {
                        carga.LoadindLabel.setText("Conección correcta...");
                    }
                    if (i == 80)
                    {
                        carga.LoadindLabel.setText("Iniciando Sistema...");
                    }
                }
                new VtnLoginVionet().setVisible(true);
            } catch (InterruptedException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
            carga.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contador;
    private javax.swing.JLabel LoadindLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
