/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import Files.Autos;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan Basilio
 */
public class VtnAutoAdmin extends javax.swing.JPanel
{

    /**
     * Creates new form VtnAutoAdmin
     */
    public VtnAutoAdmin()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        gestionaAuto = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        modelo = new javax.swing.JTextField();
        fabricante = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        anio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tipo = new javax.swing.JComboBox<>();
        transmision = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        modifModelo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        modifFabricante = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        modifPrecio = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboAuto = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        modifTransmision = new javax.swing.JComboBox<>();
        modifTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        modifID = new javax.swing.JTextField();
        modifAnio = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        buscaProducto = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        detalleAuto = new javax.swing.JTable();
        eliminaAuto = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        verAutos = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        comboTransmision = new javax.swing.JComboBox<>();
        comboAnio = new javax.swing.JComboBox<>();
        comboTipo = new javax.swing.JComboBox<>();
        comboPrecio = new javax.swing.JComboBox<>();
        comboFabricante = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gestionaAuto.setBackground(new java.awt.Color(255, 102, 0));
        gestionaAuto.setForeground(new java.awt.Color(255, 255, 255));
        gestionaAuto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gestionaAuto.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                gestionaAutoMouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 230, 30));
        jPanel3.add(fabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 230, 30));
        jPanel3.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 230, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Transmisión");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 230, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Modelo");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 230, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fabricante");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 230, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 230, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Precio");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 230, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Año");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 230, 20));
        jPanel3.add(anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 230, 30));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Materials/guardar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 500, -1, 60));

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deportivo", "Exotico", "Todoterreno", "Sedan" }));
        jPanel3.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 230, 30));

        transmision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Automatico" }));
        jPanel3.add(transmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 230, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Alta Autos");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        gestionaAuto.addTab("Alta Autos", jPanel3);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Modelo");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 230, 20));
        jPanel5.add(modifModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 230, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Fabricante");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 230, 20));
        jPanel5.add(modifFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 230, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Transmisión");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 230, 20));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Año");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 230, 20));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Tipo");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 230, 20));
        jPanel5.add(modifPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 230, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Precio");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 230, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SELECCIONA ALGÚN AUTO");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 230, -1));

        comboAuto.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboAutoItemStateChanged(evt);
            }
        });
        jPanel5.add(comboAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 230, -1));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Materials/guardar.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 500, -1, 60));

        modifTransmision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Automatico" }));
        jPanel5.add(modifTransmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 230, 30));

        modifTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deportivo", "Exotico", "Todoterreno", "Sedan" }));
        jPanel5.add(modifTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 230, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Número de Control (ID)");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 230, 30));
        jPanel5.add(modifID, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 230, 30));

        modifAnio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jPanel5.add(modifAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 230, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Modifica Autos");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        gestionaAuto.addTab("Modifica Autos", jPanel5);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Escriba algún modelo");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 130, -1));

        buscaProducto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscaProductoActionPerformed(evt);
            }
        });
        jPanel4.add(buscaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 200, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Detalles del auto");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 130, -1));

        detalleAuto.setBackground(new java.awt.Color(51, 51, 51));
        detalleAuto.setForeground(new java.awt.Color(255, 255, 255));
        detalleAuto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID", "Modelo", "Transmisión", "Año"
            }
        ));
        jScrollPane3.setViewportView(detalleAuto);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 880, 150));

        eliminaAuto.setText("ELIMINAR AUTO");
        eliminaAuto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                eliminaAutoActionPerformed(evt);
            }
        });
        jPanel4.add(eliminaAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Materials/lupa.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jButton2MouseClicked(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, -1, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Elimina Autos");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        gestionaAuto.addTab("Baja Autos", jPanel4);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verAutos.setBackground(new java.awt.Color(51, 51, 51));
        verAutos.setForeground(new java.awt.Color(255, 255, 255));
        verAutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID", "Modelo", "Transmisión", "Año", "Tipo", "Precio", "Fabricante"
            }
        ));
        jScrollPane2.setViewportView(verAutos);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 930, 300));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Autos Existentes");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 210, 20));

        btnActualizar.setBackground(new java.awt.Color(51, 51, 51));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Materials/update.png"))); // NOI18N
        btnActualizar.setToolTipText("");
        btnActualizar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel6.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 150, 60, 50));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("FILTROS");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, -1));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Transmisión");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 140, -1));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Año");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 140, -1));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Precio");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 140, -1));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Tipo");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 140, -1));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Fabricante");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 140, -1));

        comboTransmision.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboTransmisionItemStateChanged(evt);
            }
        });
        comboTransmision.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                comboTransmisionMouseClicked(evt);
            }
        });
        jPanel6.add(comboTransmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 140, -1));

        comboAnio.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboAnioItemStateChanged(evt);
            }
        });
        comboAnio.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                comboAnioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                comboAnioMouseEntered(evt);
            }
        });
        jPanel6.add(comboAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 140, -1));

        comboTipo.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboTipoItemStateChanged(evt);
            }
        });
        comboTipo.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                comboTipoMouseClicked(evt);
            }
        });
        jPanel6.add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 140, -1));

        comboPrecio.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboPrecioItemStateChanged(evt);
            }
        });
        comboPrecio.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                comboPrecioMouseClicked(evt);
            }
        });
        jPanel6.add(comboPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 140, -1));

        comboFabricante.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboFabricanteItemStateChanged(evt);
            }
        });
        comboFabricante.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                comboFabricanteMouseClicked(evt);
            }
        });
        jPanel6.add(comboFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 140, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Consulta Autos");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        gestionaAuto.addTab("Consulta Autos", jPanel6);

        add(gestionaAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        if (modelo.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Faltó por llenar el campo Modelo", "Alerta", JOptionPane.WARNING_MESSAGE);
            modelo.requestFocus();
        } else if (fabricante.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Faltó por llenar el campo Fabricante", "Alerta", JOptionPane.WARNING_MESSAGE);
            fabricante.requestFocus();
        } else if (Integer.parseInt(anio.getText()) < 1886 || Integer.parseInt(anio.getText()) > 2025)
        {
            JOptionPane.showMessageDialog(this, "Año invalido", "Alerta", JOptionPane.WARNING_MESSAGE);
            anio.requestFocus();
        } else if (Integer.parseInt(precio.getText()) < 0 || Integer.parseInt(precio.getText()) > 999999999)
        {
            JOptionPane.showMessageDialog(this, "Año invalido", "Alerta", JOptionPane.WARNING_MESSAGE);
            precio.requestFocus();
        } else
        {
            Autos a = new Autos();
            a.altaAuto(modelo, transmision, anio, tipo, precio, fabricante);
            JOptionPane.showMessageDialog(this, "Auto agregado con éxito");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        if (comboAuto.getSelectedIndex() == -1 || modifPrecio.getText().isEmpty() == true || modifAnio.getText().isEmpty() || modifFabricante.getText().isEmpty() || modifModelo.getText().isEmpty() || modifTipo.getSelectedItem().toString().isEmpty() || modifTransmision.getSelectedItem().toString().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado algún auto", "Alerta", JOptionPane.WARNING_MESSAGE);
            comboAuto.requestFocus();
        } else
        {
            Autos a = new Autos();
            a.modifAuto(comboAuto, modifID, modifModelo, modifTransmision, modifAnio, modifTipo, modifPrecio, modifFabricante);
            JOptionPane.showMessageDialog(this, "Auto modificado con éxito");
            a.consultaGeneralAuto(verAutos);
            modifID.setText("");
            modifModelo.setText("");
            modifAnio.setText("");
            modifFabricante.setText("");
            modifPrecio.setText("");
            modifTipo.setSelectedIndex(-1);
            modifTransmision.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void buscaProductoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscaProductoActionPerformed
    {//GEN-HEADEREND:event_buscaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaProductoActionPerformed

    private void eliminaAutoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_eliminaAutoActionPerformed
    {//GEN-HEADEREND:event_eliminaAutoActionPerformed
        if (buscaProducto.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Faltó por llenar el campo modelo", "Advertencia", JOptionPane.WARNING_MESSAGE);
            buscaProducto.requestFocus();
        }
        int decision = JOptionPane.showConfirmDialog(this, "Advertencia, eso borrará completamente el auto", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (decision == JOptionPane.YES_OPTION)
        {
            Autos a = new Autos();
            int opc;
            opc = a.eliminarAuto(buscaProducto, detalleAuto);
            if (opc == 0)
            {
            } else
            {
                JOptionPane.showMessageDialog(this, "Se ha eliminado el auto de la base de datos");
                eliminaAuto.setEnabled(false);
            }
        }
    }//GEN-LAST:event_eliminaAutoActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton2MouseClicked
    {//GEN-HEADEREND:event_jButton2MouseClicked
        if (buscaProducto.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese el modelo de algún auto");
            buscaProducto.requestFocus();
        } else
        {
            Autos a = new Autos();
            int flagBusca;
            flagBusca = a.buscaAutoEliminar(buscaProducto, detalleAuto);
            if (flagBusca == 0)
            {
                JOptionPane.showMessageDialog(this, "No se encontró ningún modelo con ese nombre");
            }
            eliminaAuto.setEnabled(true);

        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnActualizarActionPerformed
    {//GEN-HEADEREND:event_btnActualizarActionPerformed
        Autos a = new Autos();
        a.activarTodosCombos(comboTransmision, comboAnio, comboTipo, comboPrecio, comboFabricante);
        a.consultaGeneralAuto(verAutos);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void gestionaAutoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_gestionaAutoMouseClicked
    {//GEN-HEADEREND:event_gestionaAutoMouseClicked
        Autos a = new Autos();
        a.consultaGeneralAuto(verAutos);
        a.agregaCombo(comboAuto);
        a.agregaComboFabricante(comboFabricante);
        a.agregaComboAnio(comboAnio);
        a.agregaComboPrecio(comboPrecio);
        a.agregaComboTipo(comboTipo);
        a.agregaComboTransmision(comboTransmision);
    }//GEN-LAST:event_gestionaAutoMouseClicked

    private void comboTransmisionMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_comboTransmisionMouseClicked
    {//GEN-HEADEREND:event_comboTransmisionMouseClicked
        Autos a = new Autos();
        String campoFiltrado = "Transmision"; // Campo por el cual filtrar
        String valorFiltrado = (String) comboTransmision.getSelectedItem(); // Valor a filtrar
        a.desactivarOtrosCombos(verAutos, campoFiltrado, valorFiltrado, comboTransmision, comboTransmision, comboAnio, comboTipo, comboPrecio, comboFabricante);
    }//GEN-LAST:event_comboTransmisionMouseClicked

    private void comboAutoItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboAutoItemStateChanged
    {//GEN-HEADEREND:event_comboAutoItemStateChanged
        Autos a = new Autos();
        a.selecAuto(comboAuto, modifID, modifModelo, modifTransmision, modifAnio, modifTipo, modifPrecio, modifFabricante);
    }//GEN-LAST:event_comboAutoItemStateChanged

    private void comboAnioMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_comboAnioMouseClicked
    {//GEN-HEADEREND:event_comboAnioMouseClicked
        Autos a = new Autos();
        String campoFiltrado = "Anio"; // Campo por el cual filtrar
        String valorFiltrado = (String) comboAnio.getSelectedItem(); // Valor a filtrar
        a.desactivarOtrosCombos(verAutos, campoFiltrado, valorFiltrado, comboAnio, comboTransmision, comboAnio, comboTipo, comboPrecio, comboFabricante);
    }//GEN-LAST:event_comboAnioMouseClicked

    private void comboTipoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_comboTipoMouseClicked
    {//GEN-HEADEREND:event_comboTipoMouseClicked
        Autos a = new Autos();
        String campoFiltrado = "Tipo"; // Campo por el cual filtrar
        String valorFiltrado = (String) comboTipo.getSelectedItem(); // Valor a filtrar
        a.desactivarOtrosCombos(verAutos, campoFiltrado, valorFiltrado, comboTipo, comboTransmision, comboAnio, comboTipo, comboPrecio, comboFabricante);
    }//GEN-LAST:event_comboTipoMouseClicked

    private void comboPrecioMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_comboPrecioMouseClicked
    {//GEN-HEADEREND:event_comboPrecioMouseClicked
        Autos a = new Autos();
        String campoFiltrado = "Precio"; // Campo por el cual filtrar
        String valorFiltrado = (String) comboPrecio.getSelectedItem(); // Valor a filtrar
        a.desactivarOtrosCombos(verAutos, campoFiltrado, valorFiltrado, comboPrecio, comboTransmision, comboAnio, comboTipo, comboPrecio, comboFabricante);
    }//GEN-LAST:event_comboPrecioMouseClicked

    private void comboFabricanteMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_comboFabricanteMouseClicked
    {//GEN-HEADEREND:event_comboFabricanteMouseClicked
        Autos a = new Autos();
        String campoFiltrado = "Fabricante"; // Campo por el cual filtrar
        String valorFiltrado = (String) comboFabricante.getSelectedItem(); // Valor a filtrar
        a.desactivarOtrosCombos(verAutos, campoFiltrado, valorFiltrado, comboFabricante, comboTransmision, comboAnio, comboTipo, comboPrecio, comboFabricante);
    }//GEN-LAST:event_comboFabricanteMouseClicked

    private void comboAnioMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_comboAnioMouseEntered
    {//GEN-HEADEREND:event_comboAnioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAnioMouseEntered

    private void comboTransmisionItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboTransmisionItemStateChanged
    {//GEN-HEADEREND:event_comboTransmisionItemStateChanged
        Autos a = new Autos();
        String campoFiltrado = "Transmision"; // Campo por el cual filtrar
        String valorFiltrado = (String) comboTransmision.getSelectedItem(); // Valor a filtrar
        a.desactivarOtrosCombos(verAutos, campoFiltrado, valorFiltrado, comboTransmision, comboTransmision, comboAnio, comboTipo, comboPrecio, comboFabricante);
    }//GEN-LAST:event_comboTransmisionItemStateChanged

    private void comboAnioItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboAnioItemStateChanged
    {//GEN-HEADEREND:event_comboAnioItemStateChanged
        Autos a = new Autos();
        String campoFiltrado = "Anio"; // Campo por el cual filtrar
        String valorFiltrado = (String) comboAnio.getSelectedItem(); // Valor a filtrar
        a.desactivarOtrosCombos(verAutos, campoFiltrado, valorFiltrado, comboAnio, comboTransmision, comboAnio, comboTipo, comboPrecio, comboFabricante);
    }//GEN-LAST:event_comboAnioItemStateChanged

    private void comboTipoItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboTipoItemStateChanged
    {//GEN-HEADEREND:event_comboTipoItemStateChanged
        Autos a = new Autos();
        String campoFiltrado = "Tipo"; // Campo por el cual filtrar
        String valorFiltrado = (String) comboTipo.getSelectedItem(); // Valor a filtrar
        a.desactivarOtrosCombos(verAutos, campoFiltrado, valorFiltrado, comboTipo, comboTransmision, comboAnio, comboTipo, comboPrecio, comboFabricante);
    }//GEN-LAST:event_comboTipoItemStateChanged

    private void comboPrecioItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboPrecioItemStateChanged
    {//GEN-HEADEREND:event_comboPrecioItemStateChanged
        Autos a = new Autos();
        String campoFiltrado = "Precio"; // Campo por el cual filtrar
        String valorFiltrado = (String) comboPrecio.getSelectedItem(); // Valor a filtrar
        a.desactivarOtrosCombos(verAutos, campoFiltrado, valorFiltrado, comboPrecio, comboTransmision, comboAnio, comboTipo, comboPrecio, comboFabricante);
    }//GEN-LAST:event_comboPrecioItemStateChanged

    private void comboFabricanteItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboFabricanteItemStateChanged
    {//GEN-HEADEREND:event_comboFabricanteItemStateChanged
        Autos a = new Autos();
        String campoFiltrado = "Fabricante"; // Campo por el cual filtrar
        String valorFiltrado = (String) comboFabricante.getSelectedItem(); // Valor a filtrar
        a.desactivarOtrosCombos(verAutos, campoFiltrado, valorFiltrado, comboFabricante, comboTransmision, comboAnio, comboTipo, comboPrecio, comboFabricante);
    }//GEN-LAST:event_comboFabricanteItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anio;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JTextField buscaProducto;
    private javax.swing.JComboBox<String> comboAnio;
    private javax.swing.JComboBox<String> comboAuto;
    private javax.swing.JComboBox<String> comboFabricante;
    private javax.swing.JComboBox<String> comboPrecio;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JComboBox<String> comboTransmision;
    private javax.swing.JTable detalleAuto;
    private javax.swing.JButton eliminaAuto;
    private javax.swing.JTextField fabricante;
    private javax.swing.JTabbedPane gestionaAuto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField modelo;
    private javax.swing.JFormattedTextField modifAnio;
    private javax.swing.JTextField modifFabricante;
    private javax.swing.JTextField modifID;
    private javax.swing.JTextField modifModelo;
    private javax.swing.JTextField modifPrecio;
    private javax.swing.JComboBox<String> modifTipo;
    private javax.swing.JComboBox<String> modifTransmision;
    private javax.swing.JTextField precio;
    private javax.swing.JComboBox<String> tipo;
    private javax.swing.JComboBox<String> transmision;
    private javax.swing.JTable verAutos;
    // End of variables declaration//GEN-END:variables
}
