/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Files.Autos;
import cjb.ci.Validaciones;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan Basilio
 */
public class VtnBusqueda extends javax.swing.JFrame
{

    /**
     * Creates new form VtnBusqueda
     */
    public VtnBusqueda()
    {
        initComponents();
        /*
        comboAnioBusqueda.setEnabled(false);
        comboFabricanteBusqueda.setEnabled(false);
        comboPrecioBusqueda.setEnabled(false);
        comboTipoBusqueda.setEnabled(false);
        comboTransmisionBusqueda.setEnabled(false);
        */
    }

    private String usuario;
    private String categoria;

    public void setUsuario(String usuario)
    {
        this.usuario = usuario;
        labelUser.setText(usuario);
    }

    public void setCategoria(String categoria)
    {
        this.categoria = categoria;
        labelCategoria.setText(categoria);
    }
    
    public void repintar()
    {
        busqueda b = new busqueda();
        b.setSize(930, 440);
        b.setLocation(0, 0);
        PanelAutos.removeAll();
        PanelAutos.add(b);
        PanelAutos.revalidate();
        PanelAutos.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboFabricanteBusqueda = new javax.swing.JComboBox<>();
        comboPrecioBusqueda = new javax.swing.JComboBox<>();
        comboTipoBusqueda = new javax.swing.JComboBox<>();
        comboAnioBusqueda = new javax.swing.JComboBox<>();
        comboTransmisionBusqueda = new javax.swing.JComboBox<>();
        labelUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        busquedaAuto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelCategoria = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PanelAutos = new javax.swing.JPanel();
        labelAuto1 = new javax.swing.JLabel();
        labelModelo4 = new javax.swing.JLabel();
        labelAuto4 = new javax.swing.JLabel();
        labelAuto3 = new javax.swing.JLabel();
        labelModelo3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        labelModelo2 = new javax.swing.JLabel();
        labelAuto2 = new javax.swing.JLabel();
        labelModelo1 = new javax.swing.JLabel();
        labelAuto5 = new javax.swing.JLabel();
        labelModelo5 = new javax.swing.JLabel();
        labelAuto6 = new javax.swing.JLabel();
        labelModelo6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 702));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FILTROS");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fabricante");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 160, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Año");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 160, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Transmisión");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 160, 30));

        comboFabricanteBusqueda.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboFabricanteBusquedaItemStateChanged(evt);
            }
        });
        comboFabricanteBusqueda.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                comboFabricanteBusquedaMouseClicked(evt);
            }
        });
        comboFabricanteBusqueda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                comboFabricanteBusquedaActionPerformed(evt);
            }
        });
        comboFabricanteBusqueda.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                comboFabricanteBusquedaKeyTyped(evt);
            }
        });
        jPanel2.add(comboFabricanteBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 160, -1));

        comboPrecioBusqueda.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboPrecioBusquedaItemStateChanged(evt);
            }
        });
        comboPrecioBusqueda.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                comboPrecioBusquedaMouseClicked(evt);
            }
        });
        comboPrecioBusqueda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                comboPrecioBusquedaActionPerformed(evt);
            }
        });
        jPanel2.add(comboPrecioBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, -1));

        comboTipoBusqueda.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboTipoBusquedaItemStateChanged(evt);
            }
        });
        comboTipoBusqueda.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                comboTipoBusquedaMouseClicked(evt);
            }
        });
        comboTipoBusqueda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                comboTipoBusquedaActionPerformed(evt);
            }
        });
        jPanel2.add(comboTipoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, -1));

        comboAnioBusqueda.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboAnioBusquedaItemStateChanged(evt);
            }
        });
        comboAnioBusqueda.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                comboAnioBusquedaMouseClicked(evt);
            }
        });
        comboAnioBusqueda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                comboAnioBusquedaActionPerformed(evt);
            }
        });
        comboAnioBusqueda.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                comboAnioBusquedaKeyTyped(evt);
            }
        });
        jPanel2.add(comboAnioBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 160, -1));

        comboTransmisionBusqueda.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboTransmisionBusquedaItemStateChanged(evt);
            }
        });
        comboTransmisionBusqueda.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                comboTransmisionBusquedaMouseClicked(evt);
            }
        });
        comboTransmisionBusqueda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                comboTransmisionBusquedaActionPerformed(evt);
            }
        });
        jPanel2.add(comboTransmisionBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 630));

        labelUser.setForeground(new java.awt.Color(255, 255, 255));
        labelUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUser.setText("USUARIO");
        jPanel1.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 230, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VIONET MOTORS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 240, 30));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Materials/user.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 60, 50));

        busquedaAuto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                busquedaAutoActionPerformed(evt);
            }
        });
        busquedaAuto.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                busquedaAutoKeyTyped(evt);
            }
        });
        jPanel1.add(busquedaAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 310, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGRESAR");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Materials/flecha.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, 20));

        labelCategoria.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        labelCategoria.setForeground(new java.awt.Color(255, 255, 255));
        labelCategoria.setText("CATEGORIA");
        jPanel1.add(labelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 200, 30));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Materials/salir.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 20, 40, 40));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Materials/lupa.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 110, 50, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Busca algún Modelo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 310, -1));

        PanelAutos.setBackground(new java.awt.Color(0, 0, 0));
        PanelAutos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAuto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto1MouseClicked(evt);
            }
        });
        PanelAutos.add(labelAuto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 220, 130));

        labelModelo4.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo4.setText("Auto 4");
        labelModelo4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo4MouseClicked(evt);
            }
        });
        PanelAutos.add(labelModelo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 220, -1));

        labelAuto4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto4MouseClicked(evt);
            }
        });
        PanelAutos.add(labelAuto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 220, 130));

        labelAuto3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto3MouseClicked(evt);
            }
        });
        PanelAutos.add(labelAuto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 220, 130));

        labelModelo3.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo3.setText("Auto 3");
        labelModelo3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo3MouseClicked(evt);
            }
        });
        PanelAutos.add(labelModelo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 220, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Mercedes Benz F1");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel25MouseClicked(evt);
            }
        });
        PanelAutos.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 570, 220, -1));

        labelModelo2.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo2.setText("Auto 2");
        labelModelo2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo2MouseClicked(evt);
            }
        });
        PanelAutos.add(labelModelo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 220, -1));

        labelAuto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto2MouseClicked(evt);
            }
        });
        PanelAutos.add(labelAuto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 220, 130));

        labelModelo1.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo1.setText("Auto 1");
        labelModelo1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo1MouseClicked(evt);
            }
        });
        PanelAutos.add(labelModelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 220, -1));

        labelAuto5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto5MouseClicked(evt);
            }
        });
        PanelAutos.add(labelAuto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 220, 130));

        labelModelo5.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo5.setText("Auto 5");
        labelModelo5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo5MouseClicked(evt);
            }
        });
        PanelAutos.add(labelModelo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 220, -1));

        labelAuto6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto6.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto6MouseClicked(evt);
            }
        });
        PanelAutos.add(labelAuto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 220, 130));

        labelModelo6.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo6.setText("Auto 6");
        labelModelo6.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo6MouseClicked(evt);
            }
        });
        PanelAutos.add(labelModelo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 220, -1));

        jPanel1.add(PanelAutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 930, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void busquedaAutoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_busquedaAutoActionPerformed
    {//GEN-HEADEREND:event_busquedaAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busquedaAutoActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel3MouseClicked
    {//GEN-HEADEREND:event_jLabel3MouseClicked
        VtnInicio vi = new VtnInicio();
        vi.setVisible(true);
        vi.setUsuario(usuario);
        vi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel4MouseClicked
    {//GEN-HEADEREND:event_jLabel4MouseClicked
        VtnInicio vi = new VtnInicio();
        vi.setVisible(true);
        vi.setUsuario(usuario);
        vi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton3MouseClicked
    {//GEN-HEADEREND:event_jButton3MouseClicked
        VtnLoginVionet vtnL = new VtnLoginVionet();
        vtnL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel25MouseClicked
    {//GEN-HEADEREND:event_jLabel25MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel25MouseClicked

    private void busquedaAutoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_busquedaAutoKeyTyped
    {//GEN-HEADEREND:event_busquedaAutoKeyTyped
        Validaciones.validaAlfanumerico(evt, 23, busquedaAuto.getText());
    }//GEN-LAST:event_busquedaAutoKeyTyped

    private void comboAnioBusquedaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_comboAnioBusquedaKeyTyped
    {//GEN-HEADEREND:event_comboAnioBusquedaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAnioBusquedaKeyTyped

    private void comboFabricanteBusquedaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_comboFabricanteBusquedaKeyTyped
    {//GEN-HEADEREND:event_comboFabricanteBusquedaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFabricanteBusquedaKeyTyped

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel2MouseClicked
    {//GEN-HEADEREND:event_jPanel2MouseClicked

    }//GEN-LAST:event_jPanel2MouseClicked

    private void comboPrecioBusquedaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_comboPrecioBusquedaMouseClicked
    {//GEN-HEADEREND:event_comboPrecioBusquedaMouseClicked
        Autos a = new Autos();
        a.desactivarOtrosCombosBusqueda(comboPrecioBusqueda, comboTransmisionBusqueda, comboAnioBusqueda, comboTipoBusqueda, comboPrecioBusqueda, comboFabricanteBusqueda);
        // JLabel necesarios en la interfaz
        /*JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
        a.consultaFiltradaBusqueda("Precio", comboPrecioBusqueda.getSelectedItem().toString(), lblImagenes, lblModelos, PanelAutos);*/
    }//GEN-LAST:event_comboPrecioBusquedaMouseClicked

    private void comboPrecioBusquedaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_comboPrecioBusquedaActionPerformed
    {//GEN-HEADEREND:event_comboPrecioBusquedaActionPerformed
        Autos a = new Autos();
        a.desactivarOtrosCombosBusqueda(comboPrecioBusqueda, comboTransmisionBusqueda, comboAnioBusqueda, comboTipoBusqueda, comboPrecioBusqueda, comboFabricanteBusqueda);
        // JLabel necesarios en la interfaz
        JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
        //a.consultaFiltradaBusqueda("Precio", comboPrecioBusqueda.getSelectedItem().toString(), lblImagenes, lblModelos, PanelAutos);
    }//GEN-LAST:event_comboPrecioBusquedaActionPerformed

    private void comboTipoBusquedaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_comboTipoBusquedaMouseClicked
    {//GEN-HEADEREND:event_comboTipoBusquedaMouseClicked
        Autos a = new Autos();
        a.desactivarOtrosCombosBusqueda(comboTipoBusqueda, comboTransmisionBusqueda, comboAnioBusqueda, comboTipoBusqueda, comboPrecioBusqueda, comboFabricanteBusqueda);
        // JLabel necesarios en la interfaz
        /*JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
        a.consultaFiltradaBusqueda("Tipo", comboPrecioBusqueda.getSelectedItem().toString(), lblImagenes, lblModelos, PanelAutos);*/
    }//GEN-LAST:event_comboTipoBusquedaMouseClicked

    private void comboTipoBusquedaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_comboTipoBusquedaActionPerformed
    {//GEN-HEADEREND:event_comboTipoBusquedaActionPerformed
        Autos a = new Autos();
        a.desactivarOtrosCombosBusqueda(comboTipoBusqueda, comboTransmisionBusqueda, comboAnioBusqueda, comboTipoBusqueda, comboPrecioBusqueda, comboFabricanteBusqueda);
        // JLabel necesarios en la interfaz
        /*JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
        a.consultaFiltradaBusqueda("Tipo", comboPrecioBusqueda.getSelectedItem().toString(), lblImagenes, lblModelos, PanelAutos);*/
    }//GEN-LAST:event_comboTipoBusquedaActionPerformed

    private void comboAnioBusquedaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_comboAnioBusquedaActionPerformed
    {//GEN-HEADEREND:event_comboAnioBusquedaActionPerformed
        Autos a = new Autos();
        a.desactivarOtrosCombosBusqueda(comboAnioBusqueda, comboTransmisionBusqueda, comboAnioBusqueda, comboTipoBusqueda, comboPrecioBusqueda, comboFabricanteBusqueda);
        // JLabel necesarios en la interfaz
        /*JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
        a.consultaFiltradaBusqueda("Anio", comboPrecioBusqueda.getSelectedItem().toString(), lblImagenes, lblModelos, PanelAutos);*/
    }//GEN-LAST:event_comboAnioBusquedaActionPerformed

    private void comboAnioBusquedaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_comboAnioBusquedaMouseClicked
    {//GEN-HEADEREND:event_comboAnioBusquedaMouseClicked
        Autos a = new Autos();
        a.desactivarOtrosCombosBusqueda(comboAnioBusqueda, comboTransmisionBusqueda, comboAnioBusqueda, comboTipoBusqueda, comboPrecioBusqueda, comboFabricanteBusqueda);
        // JLabel necesarios en la interfaz
        /*JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
        a.consultaFiltradaBusqueda("Anio", comboPrecioBusqueda.getSelectedItem().toString(), lblImagenes, lblModelos, PanelAutos);*/
    }//GEN-LAST:event_comboAnioBusquedaMouseClicked

    private void comboTransmisionBusquedaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_comboTransmisionBusquedaActionPerformed
    {//GEN-HEADEREND:event_comboTransmisionBusquedaActionPerformed
        Autos a = new Autos();
        a.desactivarOtrosCombosBusqueda(comboTransmisionBusqueda, comboTransmisionBusqueda, comboAnioBusqueda, comboTipoBusqueda, comboPrecioBusqueda, comboFabricanteBusqueda);
        // JLabel necesarios en la interfaz
        /*JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
        a.consultaFiltradaBusqueda("Transmision", comboPrecioBusqueda.getSelectedItem().toString(), lblImagenes, lblModelos, PanelAutos);*/
    }//GEN-LAST:event_comboTransmisionBusquedaActionPerformed

    private void comboTransmisionBusquedaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_comboTransmisionBusquedaMouseClicked
    {//GEN-HEADEREND:event_comboTransmisionBusquedaMouseClicked
        Autos a = new Autos();
        a.desactivarOtrosCombosBusqueda(comboTransmisionBusqueda, comboTransmisionBusqueda, comboAnioBusqueda, comboTipoBusqueda, comboPrecioBusqueda, comboFabricanteBusqueda);
        // JLabel necesarios en la interfaz
        /*JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
        a.consultaFiltradaBusqueda("Transmision", comboPrecioBusqueda.getSelectedItem().toString(), lblImagenes, lblModelos, PanelAutos);*/
    }//GEN-LAST:event_comboTransmisionBusquedaMouseClicked

    private void comboFabricanteBusquedaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_comboFabricanteBusquedaActionPerformed
    {//GEN-HEADEREND:event_comboFabricanteBusquedaActionPerformed
        Autos a = new Autos();
        a.desactivarOtrosCombosBusqueda(comboFabricanteBusqueda, comboTransmisionBusqueda, comboAnioBusqueda, comboTipoBusqueda, comboPrecioBusqueda, comboFabricanteBusqueda);
        // JLabel necesarios en la interfaz
        /*JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
        a.consultaFiltradaBusqueda("Fabricante", comboPrecioBusqueda.getSelectedItem().toString(), lblImagenes, lblModelos, PanelAutos);*/
    }//GEN-LAST:event_comboFabricanteBusquedaActionPerformed

    private void comboFabricanteBusquedaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_comboFabricanteBusquedaMouseClicked
    {//GEN-HEADEREND:event_comboFabricanteBusquedaMouseClicked
        Autos a = new Autos();
        a.desactivarOtrosCombosBusqueda(comboFabricanteBusqueda, comboTransmisionBusqueda, comboAnioBusqueda, comboTipoBusqueda, comboPrecioBusqueda, comboFabricanteBusqueda);
        // JLabel necesarios en la interfaz
        /*JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
        a.consultaFiltradaBusqueda("Fabricante", comboPrecioBusqueda.getSelectedItem().toString(), lblImagenes, lblModelos, PanelAutos);*/
    }//GEN-LAST:event_comboFabricanteBusquedaMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        Autos a = new Autos();
        a.agregaComboFabricante(comboFabricanteBusqueda);
        a.agregaComboAnio(comboAnioBusqueda);
        a.agregaComboPrecio(comboPrecioBusqueda);
        a.agregaComboTipo(comboTipoBusqueda);
        a.agregaComboTransmision(comboTransmisionBusqueda);
        JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };
        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
    }//GEN-LAST:event_formWindowOpened

    private void comboPrecioBusquedaItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboPrecioBusquedaItemStateChanged
    {//GEN-HEADEREND:event_comboPrecioBusquedaItemStateChanged
        Autos a = new Autos();
        /*if (comboPrecioBusqueda.isEnabled())
        {
            
        }*/
        a.desactivarOtrosCombosBusqueda(comboPrecioBusqueda, comboTransmisionBusqueda, comboAnioBusqueda, comboTipoBusqueda, comboPrecioBusqueda, comboFabricanteBusqueda);
        // JLabel necesarios en la interfaz
        JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
        a.consultaFiltradaBusqueda("Precio", comboPrecioBusqueda.getSelectedItem().toString(), lblImagenes, lblModelos);
    }//GEN-LAST:event_comboPrecioBusquedaItemStateChanged

    private void comboTipoBusquedaItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboTipoBusquedaItemStateChanged
    {//GEN-HEADEREND:event_comboTipoBusquedaItemStateChanged
        /*if (comboPrecioBusqueda.isEnabled() == false)
        {
            this.repintar();
        }else
        {
            
        }
        
        
        /*Autos a = new Autos();
        a.desactivarOtrosCombosBusqueda(comboPrecioBusqueda, comboTransmisionBusqueda, comboAnioBusqueda, comboTipoBusqueda, comboPrecioBusqueda, comboFabricanteBusqueda);
        labelCategoria.setText(comboTipoBusqueda.getSelectedItem().toString());
        // JLabel necesarios en la interfaz
        JLabel[] lblImagenesT =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelosT =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
        a.consultaFiltradaBusqueda("Tipo", comboPrecioBusqueda.getSelectedItem().toString(), lblImagenesT, lblModelosT);*/
    }//GEN-LAST:event_comboTipoBusquedaItemStateChanged

    private void comboAnioBusquedaItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboAnioBusquedaItemStateChanged
    {//GEN-HEADEREND:event_comboAnioBusquedaItemStateChanged
        Autos a = new Autos();
        a.desactivarOtrosCombosBusqueda(comboPrecioBusqueda, comboTransmisionBusqueda, comboAnioBusqueda, comboTipoBusqueda, comboPrecioBusqueda, comboFabricanteBusqueda);
        // JLabel necesarios en la interfaz
        JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
        //a.consultaFiltradaBusqueda("Anio", comboPrecioBusqueda.getSelectedItem().toString(), lblImagenes, lblModelos);
    }//GEN-LAST:event_comboAnioBusquedaItemStateChanged

    private void comboTransmisionBusquedaItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboTransmisionBusquedaItemStateChanged
    {//GEN-HEADEREND:event_comboTransmisionBusquedaItemStateChanged
        Autos a = new Autos();
        a.desactivarOtrosCombosBusqueda(comboPrecioBusqueda, comboTransmisionBusqueda, comboAnioBusqueda, comboTipoBusqueda, comboPrecioBusqueda, comboFabricanteBusqueda);
        // JLabel necesarios en la interfaz
        JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
        //a.consultaFiltradaBusqueda("Transmision", comboPrecioBusqueda.getSelectedItem().toString(), lblImagenes, lblModelos);
    }//GEN-LAST:event_comboTransmisionBusquedaItemStateChanged

    private void comboFabricanteBusquedaItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboFabricanteBusquedaItemStateChanged
    {//GEN-HEADEREND:event_comboFabricanteBusquedaItemStateChanged
        Autos a = new Autos();
        a.desactivarOtrosCombosBusqueda(comboPrecioBusqueda, comboTransmisionBusqueda, comboAnioBusqueda, comboTipoBusqueda, comboPrecioBusqueda, comboFabricanteBusqueda);
        // JLabel necesarios en la interfaz
        JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
        //a.consultaFiltradaBusqueda("Fabricante", comboPrecioBusqueda.getSelectedItem().toString(), lblImagenes, lblModelos);
    }//GEN-LAST:event_comboFabricanteBusquedaItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };
        if (busquedaAuto.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese el modelo de algún auto");
            busquedaAuto.requestFocus();
        } else
        {
            Autos a = new Autos();
            int flagBusca;
            flagBusca = a.buscaAutoMostrar(busquedaAuto.getText(), lblImagenes, lblModelos);
            if (flagBusca == 0)
            {
                JOptionPane.showMessageDialog(this, "No se encontró ningún modelo con ese nombre");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void labelModelo3MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo3MouseClicked
    {//GEN-HEADEREND:event_labelModelo3MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelModelo3MouseClicked

    private void labelAuto3MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto3MouseClicked
    {//GEN-HEADEREND:event_labelAuto3MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelAuto3MouseClicked

    private void labelModelo6MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo6MouseClicked
    {//GEN-HEADEREND:event_labelModelo6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelModelo6MouseClicked

    private void labelAuto6MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto6MouseClicked
    {//GEN-HEADEREND:event_labelAuto6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelAuto6MouseClicked

    private void labelModelo2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo2MouseClicked
    {//GEN-HEADEREND:event_labelModelo2MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelModelo2MouseClicked

    private void labelAuto2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto2MouseClicked
    {//GEN-HEADEREND:event_labelAuto2MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelAuto2MouseClicked

    private void labelAuto5MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto5MouseClicked
    {//GEN-HEADEREND:event_labelAuto5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelAuto5MouseClicked

    private void labelModelo5MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo5MouseClicked
    {//GEN-HEADEREND:event_labelModelo5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelModelo5MouseClicked

    private void labelModelo4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo4MouseClicked
    {//GEN-HEADEREND:event_labelModelo4MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelModelo4MouseClicked

    private void labelAuto4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto4MouseClicked
    {//GEN-HEADEREND:event_labelAuto4MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelAuto4MouseClicked

    private void labelModelo1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo1MouseClicked
    {//GEN-HEADEREND:event_labelModelo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelModelo1MouseClicked

    private void labelAuto1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto1MouseClicked
    {//GEN-HEADEREND:event_labelAuto1MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelAuto1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnBusqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAutos;
    private javax.swing.JTextField busquedaAuto;
    private javax.swing.JComboBox<String> comboAnioBusqueda;
    private javax.swing.JComboBox<String> comboFabricanteBusqueda;
    private javax.swing.JComboBox<String> comboPrecioBusqueda;
    private javax.swing.JComboBox<String> comboTipoBusqueda;
    private javax.swing.JComboBox<String> comboTransmisionBusqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAuto1;
    private javax.swing.JLabel labelAuto2;
    private javax.swing.JLabel labelAuto3;
    private javax.swing.JLabel labelAuto4;
    private javax.swing.JLabel labelAuto5;
    private javax.swing.JLabel labelAuto6;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelModelo1;
    private javax.swing.JLabel labelModelo2;
    private javax.swing.JLabel labelModelo3;
    private javax.swing.JLabel labelModelo4;
    private javax.swing.JLabel labelModelo5;
    private javax.swing.JLabel labelModelo6;
    private javax.swing.JLabel labelUser;
    // End of variables declaration//GEN-END:variables
}
