/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Files.Autos;
import javax.swing.JLabel;

/**
 *
 * @author Alan Basilio
 */
public class VtnInicio extends javax.swing.JFrame
{

    /**
     * Creates new form VtnInicio
     */
    public VtnInicio()
    {
        initComponents();
    }

    private String usuario;

    public void setUsuario(String usuario)
    {
        this.usuario = usuario;
        lblUser.setText(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        labelAuto3 = new javax.swing.JLabel();
        labelAuto1 = new javax.swing.JLabel();
        labelAuto2 = new javax.swing.JLabel();
        labelAuto5 = new javax.swing.JLabel();
        labelAuto4 = new javax.swing.JLabel();
        labelAuto6 = new javax.swing.JLabel();
        labelModelo6 = new javax.swing.JLabel();
        labelModelo1 = new javax.swing.JLabel();
        labelModelo2 = new javax.swing.JLabel();
        labelModelo3 = new javax.swing.JLabel();
        labelModelo4 = new javax.swing.JLabel();
        labelModelo5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VIONET MOTORS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 310, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Materials/header.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1180, 160));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BUSQUEDA AVANZADA");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, 230, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("DEPORTIVO");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("EXOTICO");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 170, -1));

        labelAuto3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto3MouseClicked(evt);
            }
        });
        jPanel1.add(labelAuto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, 220, 130));

        labelAuto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto1MouseClicked(evt);
            }
        });
        jPanel1.add(labelAuto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 220, 130));

        labelAuto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto2MouseClicked(evt);
            }
        });
        jPanel1.add(labelAuto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 220, 130));

        labelAuto5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto5MouseClicked(evt);
            }
        });
        jPanel1.add(labelAuto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 220, 130));

        labelAuto4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto4MouseClicked(evt);
            }
        });
        jPanel1.add(labelAuto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 220, 130));

        labelAuto6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelAuto6.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelAuto6MouseClicked(evt);
            }
        });
        jPanel1.add(labelAuto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 470, 220, 130));

        labelModelo6.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo6.setText("Auto 6");
        labelModelo6.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo6MouseClicked(evt);
            }
        });
        jPanel1.add(labelModelo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 610, 220, -1));

        labelModelo1.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo1.setText("Auto 1");
        labelModelo1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo1MouseClicked(evt);
            }
        });
        jPanel1.add(labelModelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 220, -1));

        labelModelo2.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo2.setText("Auto 2");
        labelModelo2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo2MouseClicked(evt);
            }
        });
        jPanel1.add(labelModelo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 220, -1));

        labelModelo3.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo3.setText("Auto 3");
        labelModelo3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo3MouseClicked(evt);
            }
        });
        jPanel1.add(labelModelo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, 220, -1));

        labelModelo4.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo4.setText("Auto 4");
        labelModelo4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo4MouseClicked(evt);
            }
        });
        jPanel1.add(labelModelo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, 220, -1));

        labelModelo5.setForeground(new java.awt.Color(255, 255, 255));
        labelModelo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModelo5.setText("Auto 5");
        labelModelo5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelModelo5MouseClicked(evt);
            }
        });
        jPanel1.add(labelModelo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 610, 220, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Materials/user.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 50, 50));

        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUser.setText("USUARIO");
        lblUser.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblUserMouseClicked(evt);
            }
        });
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 130, 30));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Materials/salir.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, 40, 40));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("TODOTERRENO");
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 170, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("SEDAN");
        jButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        VtnBusqueda vb = new VtnBusqueda();
        vb.setVisible(true);
        vb.setUsuario(usuario);
        vb.setVisible(true);
        String categoria = "CATEGORIA";
        vb.setCategoria(categoria);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        VtnBusqueda vb = new VtnBusqueda();
        vb.setVisible(true);
        vb.setUsuario(usuario);
        vb.setVisible(true);
        String categoria = "DEPORTIVO";
        vb.setCategoria(categoria);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        VtnBusqueda vb = new VtnBusqueda();
        vb.setVisible(true);
        vb.setUsuario(usuario);
        vb.setVisible(true);
        String categoria = "EXOTICO";
        vb.setCategoria(categoria);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void labelAuto1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto1MouseClicked
    {//GEN-HEADEREND:event_labelAuto1MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelAuto1MouseClicked

    private void labelModelo1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo1MouseClicked
    {//GEN-HEADEREND:event_labelModelo1MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelModelo1MouseClicked

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblUserMouseClicked
    {//GEN-HEADEREND:event_lblUserMouseClicked

    }//GEN-LAST:event_lblUserMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton4MouseClicked
    {//GEN-HEADEREND:event_jButton4MouseClicked
        VtnLoginVionet vtnL = new VtnLoginVionet();
        vtnL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void labelAuto2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto2MouseClicked
    {//GEN-HEADEREND:event_labelAuto2MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelAuto2MouseClicked

    private void labelAuto3MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto3MouseClicked
    {//GEN-HEADEREND:event_labelAuto3MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelAuto3MouseClicked

    private void labelAuto4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto4MouseClicked
    {//GEN-HEADEREND:event_labelAuto4MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelAuto4MouseClicked

    private void labelAuto5MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto5MouseClicked
    {//GEN-HEADEREND:event_labelAuto5MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelAuto5MouseClicked

    private void labelAuto6MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelAuto6MouseClicked
    {//GEN-HEADEREND:event_labelAuto6MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelAuto6MouseClicked

    private void labelModelo2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo2MouseClicked
    {//GEN-HEADEREND:event_labelModelo2MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelModelo2MouseClicked

    private void labelModelo3MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo3MouseClicked
    {//GEN-HEADEREND:event_labelModelo3MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelModelo3MouseClicked

    private void labelModelo4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo4MouseClicked
    {//GEN-HEADEREND:event_labelModelo4MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelModelo4MouseClicked

    private void labelModelo5MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo5MouseClicked
    {//GEN-HEADEREND:event_labelModelo5MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelModelo5MouseClicked

    private void labelModelo6MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelModelo6MouseClicked
    {//GEN-HEADEREND:event_labelModelo6MouseClicked
        VtnAuto va  = new VtnAuto();
        va.setVisible(true);
        va.setUsuario(usuario);
        va.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelModelo6MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        VtnBusqueda vb = new VtnBusqueda();
        vb.setVisible(true);
        vb.setUsuario(usuario);
        vb.setVisible(true);
        String categoria = "TODOTERRENO";
        vb.setCategoria(categoria);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton6ActionPerformed
    {//GEN-HEADEREND:event_jButton6ActionPerformed
        VtnBusqueda vb = new VtnBusqueda();
        vb.setVisible(true);
        vb.setUsuario(usuario);
        vb.setVisible(true);
        String categoria = "SEDAN";
        vb.setCategoria(categoria);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // JLabel necesarios en la interfaz
        JLabel[] lblImagenes =
        {
            labelAuto1, labelAuto2, labelAuto3, labelAuto4, labelAuto5, labelAuto6
        };

        JLabel[] lblModelos =
        {
            labelModelo1, labelModelo2, labelModelo3, labelModelo4, labelModelo5, labelModelo6
        };

// Crear una instancia de AutoDisplay y llamar al método mostrarAutos
        Autos a = new Autos();
        a.mostrarAutos(lblImagenes, lblModelos);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAuto1;
    private javax.swing.JLabel labelAuto2;
    private javax.swing.JLabel labelAuto3;
    private javax.swing.JLabel labelAuto4;
    private javax.swing.JLabel labelAuto5;
    private javax.swing.JLabel labelAuto6;
    private javax.swing.JLabel labelModelo1;
    private javax.swing.JLabel labelModelo2;
    private javax.swing.JLabel labelModelo3;
    private javax.swing.JLabel labelModelo4;
    private javax.swing.JLabel labelModelo5;
    private javax.swing.JLabel labelModelo6;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
